//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exercicio03.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class Produto
    {
        public int ProdutoId { get; set; }
        [Display(Name="Data de Cadastro")]
        public System.DateTime DataCadastro { get; set; }
        public decimal Valor { get; set; }
        public string Descricao { get; set; }
        public string Titulo { get; set; }
        public bool Nacional { get; set; }
    }
}
